// Seeded pickleball courts in Austin, TX area
// Realistic data for testing and demo purposes
export const SEED_COURTS = [
  {
    name: "Pan American Park",
    address: "2100 E 3rd St, Austin, TX 78702",
    lat: 30.2551,
    lng: -97.7219,
    indoor: false,
    surface_type: "asphalt",
    num_courts: 6,
    amenities: ["lights", "parking", "restrooms"],
    verified: true,
  },
  {
    name: "South Austin Recreation Center",
    address: "1100 Cumberland Rd, Austin, TX 78704",
    lat: 30.2385,
    lng: -97.7662,
    indoor: true,
    surface_type: "sport_court",
    num_courts: 4,
    amenities: ["restrooms", "parking", "water"],
    verified: true,
  },
  {
    name: "Zilker Park",
    address: "2100 Barton Springs Rd, Austin, TX 78746",
    lat: 30.2669,
    lng: -97.7704,
    indoor: false,
    surface_type: "asphalt",
    num_courts: 8,
    amenities: ["parking", "restrooms", "lights", "water"],
    verified: true,
  },
  {
    name: "Dick Nichols District Park",
    address: "8011 Beckett Rd, Austin, TX 78749",
    lat: 30.2147,
    lng: -97.8423,
    indoor: false,
    surface_type: "concrete",
    num_courts: 4,
    amenities: ["parking", "restrooms", "lights"],
    verified: true,
  },
  {
    name: "Northwest Recreation Center",
    address: "2913 Northland Dr, Austin, TX 78757",
    lat: 30.3675,
    lng: -97.7377,
    indoor: true,
    surface_type: "sport_court",
    num_courts: 6,
    amenities: ["restrooms", "parking", "water", "ac"],
    verified: true,
  },
  {
    name: "East Austin Pickleball Complex",
    address: "3001 Webberville Rd, Austin, TX 78702",
    lat: 30.2482,
    lng: -97.7036,
    indoor: true,
    surface_type: "sport_court",
    num_courts: 12,
    amenities: ["lights", "restrooms", "parking", "water", "pro shop"],
    verified: true,
  },
  {
    name: "Mueller Lake Park",
    address: "4550 Mueller Blvd, Austin, TX 78723",
    lat: 30.2989,
    lng: -97.7074,
    indoor: false,
    surface_type: "concrete",
    num_courts: 4,
    amenities: ["parking", "water"],
    verified: true,
  },
  {
    name: "Onion Creek Metropolitan Park",
    address: "7001 Onion Creek Dr, Austin, TX 78744",
    lat: 30.1519,
    lng: -97.7561,
    indoor: false,
    surface_type: "asphalt",
    num_courts: 6,
    amenities: ["parking", "restrooms", "lights"],
    verified: true,
  },
  {
    name: "Bartholomew Park",
    address: "5201 Berkman Dr, Austin, TX 78723",
    lat: 30.3141,
    lng: -97.6888,
    indoor: false,
    surface_type: "concrete",
    num_courts: 4,
    amenities: ["parking", "restrooms", "lights", "water"],
    verified: true,
  },
  {
    name: "Walnut Creek Park",
    address: "12138 N Lamar Blvd, Austin, TX 78753",
    lat: 30.3989,
    lng: -97.6896,
    indoor: false,
    surface_type: "asphalt",
    num_courts: 6,
    amenities: ["parking", "restrooms", "lights"],
    verified: true,
  },
  {
    name: "Circle C Park",
    address: "6301 W Slaughter Ln, Austin, TX 78749",
    lat: 30.1913,
    lng: -97.8742,
    indoor: false,
    surface_type: "asphalt",
    num_courts: 4,
    amenities: ["parking", "water"],
    verified: true,
  },
  {
    name: "Garrison Park",
    address: "6001 Manchaca Rd, Austin, TX 78745",
    lat: 30.2149,
    lng: -97.7951,
    indoor: false,
    surface_type: "concrete",
    num_courts: 4,
    amenities: ["parking", "restrooms"],
    verified: true,
  },
  {
    name: "West Austin Pickleball Center",
    address: "2901 S Capital of Texas Hwy, Austin, TX 78746",
    lat: 30.3114,
    lng: -97.8231,
    indoor: true,
    surface_type: "sport_court",
    num_courts: 10,
    amenities: ["restrooms", "parking", "water", "ac", "pro shop", "lights"],
    verified: true,
  },
  {
    name: "Yarrabee Park",
    address: "1400 Broadmoor Dr, Austin, TX 78723",
    lat: 30.3045,
    lng: -97.7148,
    indoor: false,
    surface_type: "asphalt",
    num_courts: 2,
    amenities: ["parking"],
    verified: true,
  },
  {
    name: "Brushy Creek Sports Park",
    address: "2310 Brushy Creek Rd, Cedar Park, TX 78613",
    lat: 30.5114,
    lng: -97.8087,
    indoor: false,
    surface_type: "concrete",
    num_courts: 10,
    amenities: ["parking", "restrooms", "lights", "water"],
    verified: true,
  },
  {
    name: "Lakeway Activity Center",
    address: "105 Cross Creek, Lakeway, TX 78734",
    lat: 30.3655,
    lng: -97.9863,
    indoor: true,
    surface_type: "sport_court",
    num_courts: 6,
    amenities: ["restrooms", "parking", "water", "ac"],
    verified: true,
  },
  {
    name: "Round Rock Pickleball Center",
    address: "301 W Bagdad Ave, Round Rock, TX 78664",
    lat: 30.5094,
    lng: -97.6789,
    indoor: true,
    surface_type: "sport_court",
    num_courts: 8,
    amenities: ["restrooms", "parking", "water", "ac", "pro shop"],
    verified: true,
  },
  {
    name: "San Gabriel Park",
    address: "445 E Morrow St, Georgetown, TX 78626",
    lat: 30.6366,
    lng: -97.6707,
    indoor: false,
    surface_type: "asphalt",
    num_courts: 6,
    amenities: ["parking", "restrooms", "lights", "water"],
    verified: true,
  },
  {
    name: "Pflugerville Recreation Center",
    address: "400 Immanuel Rd, Pflugerville, TX 78660",
    lat: 30.4418,
    lng: -97.6213,
    indoor: true,
    surface_type: "sport_court",
    num_courts: 4,
    amenities: ["restrooms", "parking", "water", "ac"],
    verified: true,
  },
  {
    name: "Wells Branch Community Center",
    address: "3000 Shoreline Dr, Austin, TX 78728",
    lat: 30.4478,
    lng: -97.6972,
    indoor: false,
    surface_type: "concrete",
    num_courts: 4,
    amenities: ["parking", "restrooms", "water"],
    verified: true,
  },
  {
    name: "Buda Sports Complex",
    address: "1100 Cabelas Dr, Buda, TX 78610",
    lat: 30.0817,
    lng: -97.8340,
    indoor: false,
    surface_type: "concrete",
    num_courts: 6,
    amenities: ["parking", "restrooms", "lights", "water"],
    verified: true,
  },
  {
    name: "Kyle Community Center",
    address: "700 S Front St, Kyle, TX 78640",
    lat: 29.9881,
    lng: -97.8762,
    indoor: true,
    surface_type: "sport_court",
    num_courts: 4,
    amenities: ["restrooms", "parking", "water", "ac"],
    verified: true,
  },
  {
    name: "Dittmar Recreation Center",
    address: "1009 W Dittmar Rd, Austin, TX 78745",
    lat: 30.2038,
    lng: -97.7788,
    indoor: true,
    surface_type: "sport_court",
    num_courts: 3,
    amenities: ["restrooms", "parking", "water"],
    verified: true,
  },
  {
    name: "Little Walnut Creek Sports Complex",
    address: "5301 Little Walnut Creek Dr, Austin, TX 78723",
    lat: 30.3206,
    lng: -97.7094,
    indoor: false,
    surface_type: "concrete",
    num_courts: 4,
    amenities: ["parking", "restrooms", "lights"],
    verified: true,
  },
  {
    name: "Fitzhugh Park",
    address: "6411 Fitzhugh Rd, Dripping Springs, TX 78620",
    lat: 30.1733,
    lng: -97.9863,
    indoor: false,
    surface_type: "asphalt",
    num_courts: 4,
    amenities: ["parking"],
    verified: true,
  },
  {
    name: "Mary Moore Searight Park",
    address: "907 W Slaughter Ln, Austin, TX 78748",
    lat: 30.1824,
    lng: -97.8021,
    indoor: false,
    surface_type: "concrete",
    num_courts: 4,
    amenities: ["parking", "restrooms", "lights", "water"],
    verified: true,
  },
  {
    name: "Riverside Park",
    address: "300 S Lakeshore Blvd, Austin, TX 78741",
    lat: 30.2443,
    lng: -97.7182,
    indoor: false,
    surface_type: "asphalt",
    num_courts: 2,
    amenities: ["parking"],
    verified: false,
  },
  {
    name: "MetCenter YMCA",
    address: "1012 W Ben White Blvd, Austin, TX 78704",
    lat: 30.2328,
    lng: -97.7759,
    indoor: true,
    surface_type: "sport_court",
    num_courts: 2,
    amenities: ["restrooms", "parking", "water", "ac"],
    verified: true,
  },
  {
    name: "Austin Tennis & Pickleball Center",
    address: "7800 Johnny Morris Rd, Austin, TX 78724",
    lat: 30.2793,
    lng: -97.6491,
    indoor: false,
    surface_type: "concrete",
    num_courts: 16,
    amenities: ["parking", "restrooms", "water", "lights", "pro shop"],
    verified: true,
  },
  {
    name: "Shipe Park",
    address: "4400 Avenue G, Austin, TX 78751",
    lat: 30.3118,
    lng: -97.7248,
    indoor: false,
    surface_type: "asphalt",
    num_courts: 4,
    amenities: ["parking", "restrooms"],
    verified: true,
  },
  {
    name: "Williamson County Southwest Sports Complex",
    address: "1705 Sunchase Blvd, Cedar Park, TX 78641",
    lat: 30.4872,
    lng: -97.8390,
    indoor: false,
    surface_type: "concrete",
    num_courts: 8,
    amenities: ["parking", "restrooms", "lights", "water"],
    verified: true,
  },
  {
    name: "Katherine Fleischer Park",
    address: "4801 W 64th St, Austin, TX 78731",
    lat: 30.3531,
    lng: -97.7782,
    indoor: false,
    surface_type: "asphalt",
    num_courts: 4,
    amenities: ["parking", "lights"],
    verified: true,
  },
  {
    name: "Joslin Park",
    address: "7205 S 1st St, Austin, TX 78745",
    lat: 30.1964,
    lng: -97.7903,
    indoor: false,
    surface_type: "concrete",
    num_courts: 4,
    amenities: ["parking", "water"],
    verified: true,
  },
  {
    name: "NW YMCA",
    address: "5807 McNeil Dr, Austin, TX 78729",
    lat: 30.4415,
    lng: -97.7512,
    indoor: true,
    surface_type: "sport_court",
    num_courts: 4,
    amenities: ["restrooms", "parking", "water", "ac"],
    verified: true,
  },
  {
    name: "Beverly S. Sheffield Education Center",
    address: "8212 Brodie Ln, Austin, TX 78745",
    lat: 30.1877,
    lng: -97.8175,
    indoor: false,
    surface_type: "asphalt",
    num_courts: 4,
    amenities: ["parking", "restrooms"],
    verified: true,
  },
  {
    name: "Cat Hollow Park",
    address: "9000 O'Connor Dr, Round Rock, TX 78681",
    lat: 30.5137,
    lng: -97.7228,
    indoor: false,
    surface_type: "concrete",
    num_courts: 6,
    amenities: ["parking", "restrooms", "lights", "water"],
    verified: true,
  },
];
